### ISSUE TITLE
Conflict with Raiding Expanded

### ISSUE THREAD

**Issue by Galgamins** [SeineEloquenz/jarls-of-india-ck3#8]
I don't know how, but having this mod and Raiding Expanded (https://steamcommunity.com/sharedfiles/filedetails/?id=2427479151) with the order:

1) Jarls of India
2) Raiding Expanded

causes Raiding Expanded to not work.

**Comment by SeineEloquenz** [comment]
I'm gonna look into this right away

**Comment by SeineEloquenz** [comment]
Could you point me to a bookmark and character where raiding in this combination should work but doesn't? Because I can't reproduce the issue as of yet.

**Comment by HenryZhu123** [comment]
I was using the 1066 Rags to Riches, Bohemia start. Used debug console to add piety and and make a new religion with the Unrelenting Faith tenet. Without Jarls of India, this allows the character to raise their armies as raiders. With Jarls of India, this isn't possible.

**Comment by SeineEloquenz** [comment]
This is a conflict that I can not fix in the Mod.
Both mods override the ```can_raid_trigger```.
I can provide a compatibility patch, but won't be able to keep it in sync with the original mod, should changes occur.

**Comment by HenryZhu123** [comment]
Thanks for looking into it and finding it so quickly! I think compatibility patch is a good solution for now.

**Comment by SeineEloquenz** [comment]
I've published a compatibility patch at https://steamcommunity.com/sharedfiles/filedetails/?id=2452046316
This will not be actively maintained and might break anytime Raiding expanded makes breaking changes.

**Comment by HenryZhu123** [comment]
Thank you very much!
